parameters:
    enhavo_slider.form.type.slider_order.class: Enhavo\Bundle\SliderBundle\Form\Type\SlideOrderType

services:
    enhavo_slider_slide:
        class: Enhavo\Bundle\SliderBundle\Form\Type\SlideType
        arguments:
            - '%enhavo_slider.model.slide.class%'
            - '%enhavo_translation.translate%'
        tags:
            - { name: form.type }

    enhavo_slider_slider:
        class: Enhavo\Bundle\SliderBundle\Form\Type\SliderType
        arguments:
            - '%enhavo_slider.model.slider.class%'
        tags:
            - { name: form.type }

    enhavo_slider_slider.widget.slider:
        class: Enhavo\Bundle\SliderBundle\Widget\SliderWidget
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.theme_widget, alias: slider }


    enhavo_slider.extend_listener.slider:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\SliderBundle\Entity\Slider
            - '%enhavo_slider.model.slider.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_slider.extend_listener.slide:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\SliderBundle\Entity\Slide
            - '%enhavo_slider.model.slide.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_slider.menu_builder.slider:
        class: Enhavo\Bundle\SliderBundle\Menu\SliderMenuBuilder
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.menu, alias: slider }