Enhavo\Bundle\ShopBundle\Entity\Order:
    properties:
        promotionCoupon:
            - NotNull: { groups: [redeem] }
        payment:
            - NotNull: { groups: [payment, confirm] }

    constraints:
        - Enhavo\Bundle\ShopBundle\Validator\Constraints\OrderAddressing:
            groups: [shipping]
        - Enhavo\Bundle\ShopBundle\Validator\Constraints\OrderPayment:
            groups: [payment]

Enhavo\Bundle\ShopBundle\Entity\Product:
    properties:
        title:
            - NotNull: { groups: [edit] }
        code:
            - NotNull: { groups: [edit] }

Sylius\Component\Addressing\Model\Address:
    properties:
        firstName:
            - NotBlank: { groups: [shipping] }
        lastName:
            - NotBlank: { groups: [shipping] }
        street:
            - NotBlank: { groups: [shipping] }
        city:
            - NotBlank: { groups: [shipping] }
        postcode:
            - NotBlank: { groups: [shipping] }
        countryCode:
            - NotBlank: { groups: [shipping] }