Enhavo\Bundle\ShopBundle\Entity\ProductVariant:
    type: entity
    table: shop_product_variant

    fields:
        variantPrice:
            type: integer
            nullable: true

        variantHeight:
            type: integer
            nullable: true

        variantWidth:
            type: integer
            nullable: true

        variantDepth:
            type: integer
            nullable: true

        variantVolume:
            type: integer
            nullable: true

        variantWeight:
            type: integer
            nullable: true

    manyToOne:
        picture:
            targetEntity: Enhavo\Bundle\MediaBundle\Model\FileInterface

        taxRate:
            cascade: ['persist']
            targetEntity: Sylius\Component\Taxation\Model\TaxRateInterface

    lifecycleCallbacks: {  }
