Enhavo\Bundle\ShopBundle\Entity\Order:
    type: entity
    table: shop_product_variant

    fields:
        price:
            type: integer
            nullable: true

        height:
            type: integer
            nullable: true

        width:
            type: integer
            nullable: true

        depth:
            type: integer
            nullable: true

        volume:
            type: integer
            nullable: true

        weight:
            type: integer
            nullable: true

    manyToOne:
        picture:
            targetEntity: Enhavo\Bundle\MediaBundle\Model\FileInterface

        taxRate:
            cascade: ['persist']
            targetEntity: Sylius\Component\Taxation\Model\TaxRateInterface

    lifecycleCallbacks: {  }
